### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by drmenzelit** [alexandreelise/plg_system_contentcustomfilter#1] opened 2021-04-29 12:41 UTC
Hi Alexandre, I downloaded the zip, but I'm unable to install it, I got this:

![grafik](https://user-images.githubusercontent.com/9153168/116552158-03dbed80-a8f9-11eb-8a44-0ee081b50793.png)

**Comment by alexandreelise** [comment] 2021-04-29 18:37
Hi Viviana @drmenzelit,
Which version of Joomla! do you use?
What is your system configuration? 
Can you please provide these informations please so I can help you

**Comment by drmenzelit** [comment] 2021-04-30 07:17
I have the last J4 version ‎4.0.0-beta8-dev (directly pulled from github) on a Linux Mint 5.7.3 with Apache/2.4.41 (Ubuntu) and mysql 8.0.23-0ubuntu0.20.04.1

**Comment by alexandreelise** [comment] 2021-04-30 13:45
ok. one more thing. which version of php do you use?

**Comment by drmenzelit** [comment] 2021-04-30 13:46
Sorry, PHP 7.4.3

**Comment by alexandreelise** [comment] 2021-04-30 13:52
maybe it doesn't work because you use the dev version i know it is the latest nigthly but this plugin has been tested only on verified releases and the latest verified release at the moment is 4.0.0-beta7  without the dev part at the end. When the 4.0.0-beta8 will be released verified please try again and tell me if you have the same issue @drmenzelit

**Comment by alexandreelise** [comment] 2021-04-30 15:52
I'll look into it but at first sight, it might be that your latest cutting edge version of joomla might be unstable at least for now

**Comment by alexandreelise** [comment] 2021-04-30 16:44
@drmenzelit Did you know that the latest stable version of php7.4 is php7.4.16 and that MySQL 8.0.24 is also available as the lastest stable MySQL 8 release? It's just to be more "secure" to have the latest versions if you can afford it  for your system.

**Comment by drmenzelit** [comment] 2021-04-30 16:49
I always try to be up-to-date, but I install what my package manager offers me. I have Linux Mint on my notebook, it not a "live" server ;-) But very useful to work with Joomla and better than XAMPP on my Windows desktop.

**Comment by alexandreelise** [comment] 2021-04-30 16:50
Ok I understand

**Comment by alexandreelise** [comment] 2021-05-01 03:44
Hello viviana,
I tried to reproduce your issue with an environment as close as yours as I could do with docker:
The enviromnent is debian buster (debian 10)  apache 2.4.38 php7.4.3 and the lastest version of joomla 4 beta 8 -dev pull from the repo and it installed just fine.
Try to make a fresh install of joomla. I am closing this issue for now. Feel free to reopen it if it doesn't help.

**Closed as completed by alexandreelise** 2021-05-01 03:44 UTC
